name: Auto Tweet Using AI

on:
  schedule:
    - cron: "30 6 * * *"   # 12:00 PM IST
    - cron: "30 12 * * *"  # 6:00 PM IST
    - cron: "30 18 * * *"  # 12:00 AM IST
  workflow_dispatch:

jobs:
  build:
    name: Auto Tweet Using AI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - name: Install Dependencies
        run: npm i
      - name: Run Twitter bot
        run: npm start
